# Generated by Django 3.2 on 2022-01-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrestoApp', '0002_categorymenu_itemmenu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymenu',
            old_name='name',
            new_name='title',
        ),
    ]
