# Generated by Django 3.2 on 2022-01-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrestoApp', '0003_rename_name_categorymenu_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmenu',
            old_name='name',
            new_name='title',
        ),
    ]
