# Generated by Django 3.2 on 2022-01-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrestoApp', '0004_rename_name_itemmenu_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmenu',
            old_name='price',
            new_name='price1',
        ),
        migrations.AddField(
            model_name='itemmenu',
            name='price2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemmenu',
            name='price3',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
